version: '3.7'

services:
  php8-sf6:
    container_name: php8-sf6
    build: php8-sf6
    ports:
      - "9000:8000"
    volumes:
      - ./project:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mon_mot_de_passe
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  mailer:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  db-data:
